version: '3'
services:
  bot_dezgo_gen:
    build: app/
    env_file:
      - app/.env
    restart: always

  postgres_db:
    container_name: postgres_db
    image: postgres:13
    env_file:
      -  app/.env
    ports:
      - '5432:5432'


