"""rev4

Revision ID: 62d97242e8a7
Revises: fcb742ec82b6
Create Date: 2023-11-24 02:31:50.476363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d97242e8a7'
down_revision: Union[str, None] = 'fcb742ec82b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tender', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender', 'status')
    # ### end Alembic commands ###
