"""rev2

Revision ID: 75199e76c1a0
Revises: 8764cf1fcedc
Create Date: 2023-11-24 00:13:12.854234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75199e76c1a0'
down_revision: Union[str, None] = '8764cf1fcedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'submitted_tender', ['id'])
    op.create_unique_constraint(None, 'tender', ['registration_number'])
    op.create_unique_constraint(None, 'worked_tender', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worked_tender', type_='unique')
    op.drop_constraint(None, 'tender', type_='unique')
    op.drop_constraint(None, 'submitted_tender', type_='unique')
    # ### end Alembic commands ###
