"""rev3

Revision ID: fcb742ec82b6
Revises: 75199e76c1a0
Create Date: 2023-11-24 01:35:03.907379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb742ec82b6'
down_revision: Union[str, None] = '75199e76c1a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tender', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tender', type_='unique')
    # ### end Alembic commands ###
